export const SET_NETWORK_CONNECTIVITY = 'SET_NETWORK_CONNECTIVITY';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_TAB_VISSIBILITY = 'TOGGLE_TAB_VISSIBILITY';
export const SET_USER_LOGIN_STATE = 'SET_USER_LOGIN_STATE';


// chat 
export const FETCH_CHAT_LIST = 'FETCH_CHAT_LIST';
export const FETCH_CHAT_LIST_RESOLVED = 'FETCH_CHAT_LIST_RESOLVED';
export const FETCH_CHAT_LIST_REJECTED = 'FETCH_CHAT_LIST_REJECTED';
export const TOGGLE_CHAT_SELECTION = 'TOGGLE_CHAT_SELECTION';
export const REMOVE_CHAT_SELECTION = 'REMOVE_CHAT_SELECTION';