export const SET_NETWORK_CONNECTIVITY = 'SET_NETWORK_CONNECTIVITY';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_TAB_VISSIBILITY = 'TOGGLE_TAB_VISSIBILITY';
export const SET_USER_LOGIN_STATE = 'SET_USER_LOGIN_STATE';


// chat 
export const FETCH_CHAT_LIST = 'FETCH_CHAT_LIST';
export const FETCH_CHAT_LIST_RESOLVED = 'FETCH_CHAT_LIST_RESOLVED';
export const FETCH_CHAT_LIST_REJECTED = 'FETCH_CHAT_LIST_REJECTED';
export const TOGGLE_CHAT_SELECTION = 'TOGGLE_CHAT_SELECTION';
export const REMOVE_CHAT_SELECTION = 'REMOVE_CHAT_SELECTION';

// users list 
export const FETCH_USER_WITH_SECTIONS = 'FETCH_USER_WITH_SECTIONS';
export const FETCH_USER_WITH_SECTIONS_REJECTED = 'FETCH_USER_WITH_SECTIONS_REJECTED';
export const FETCH_USER_WITH_SECTIONS_RESOLVED = 'FETCH_USER_WITH_SECTIONS_RESOLVED';

// group creation
export const ADD_USER_FOR_GROUP_CREATION = 'ADD_USER_FOR_GROUP_CREATION';
export const REMOVE_USER_FOR_GROUP_CREATION = 'REMOVE_USER_FOR_GROUP_CREATION';

// statusbar
export const TOGGLE_STATUS_BAR = 'TOGGLE_STATUS_BAR';
export const SET_APP_FORE_BACK_GROUND_STATUS = 'SET_APP_FORE_BACK_GROUND_STATUS';