export const SET_NETWORK_CONNECTIVITY = 'SET_NETWORK_CONNECTIVITY';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_TAB_VISSIBILITY = 'TOGGLE_TAB_VISSIBILITY';
export const SET_USER_LOGIN_STATE = 'SET_USER_LOGIN_STATE';