export const APP_TAB = 'APP_TAB';

// screens
export const CONTACT_DETAILS_SCREEN = 'CONTACT_DETAILS_SCREEN';
export const CALL_HISTORY_SCREEN = 'CALL_HISTORY_SCREEN';
export const CAMERA_SCREEN = 'CAMERA_SCREEN';
export const CHATS_SCREEN = 'CHATS_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const STATUS_SCREEN = 'STATUS_SCREEN';
export const HELP_CENTER_SCREEN = 'HELP_CENTER_SCREEN';
export const LICENCSES_CENTER_SCREEN = 'LICENCSES_CENTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';

// routes
export const MAIN_ROUTE = 'MAIN_ROUTE';
export const AUTH_ROUTE = 'AUTH_ROUTE';
export const HELP_ROUTE = 'HELP_ROUTE';